src/blockdata.rs
src/signer_node.rs
src/timer.rs

Fix round timer behavior. The timer behavior didn't have consistent policy. So, it worked inconsistent way.
After this PR, Round timer must follow below basically rule.
* The timer is started on rounds start only.
* New round is started on only receiving completedblock message or previous round is timeout.

Fix round timer

---

src/bin/tapyrus-signerd.rs
src/signer_node.rs

This PR fixes #30
This PR also includes to make node process avoid to truncate log file when the process started.

Make signer node has idle time before starting Key Generation Protocol communication

---

Cargo.lock
Cargo.toml
src/crypto/mod.rs
src/crypto/multi_party_schnorr.rs
src/crypto/test_multi_party_schnorr.rs
src/errors.rs
src/lib.rs
src/sign.rs
src/signer_node/message_processor/process_blocksig.rs
src/signer_node/message_processor/process_blockvss.rs
src/signer_node/message_processor/process_candidateblock.rs
src/signer_node/mod.rs
src/signer_node/node_parameters.rs

Files changed includes #34, #35, #37 
It is enough to review 2 commits( 0c531b2 and 51df7dc).
It was because the hash function used in compute and verify schnorr signature code receive message as BigInt. You can read more details in #32.
This PR moved multi party schnorr signature cryptography codes from multi_party_schnorr into this repo. Its target is bip-schnorr but our protocol is different from that. So, I copied and we are going to extend it.

Fix generating wrong signature.

---

README.md

Repository of Tapyrus Core is https://github.com/chaintope/tapyrus-core

Fix repository url

---

src/blockdata.rs

We should support use case where the block has an aggregated public key.

Fix sighash() in case the block has agg pubkey.

---

src/sign.rs

fix #88
Secp256k1Scalar::new_random() has potential to generate invalid secret key.

Change to use secp256k1::SecretKey::new() to generate random secret key.

---

src/rpc.rs

this option was removed for relaxing tx standard rule.

Remove acceptnonstdtxn option when calling testporposedblock rpc.

---

src/net.rs

It already works like this, if all public key is compressed format. 
This change make it guarantees this behavior.

Ensure a vector of SignerID would be sorted by compressed 33 bytes format.

---

src/command_args.rs

Signed-off-by: Kohei Taniguchi <kohei@chaintope.com>

Eliminate outdated fields private key and public keys from signer config toml.

---

src/bin/tapyrus-signerd.rs
src/federation.rs
src/signer_node/message_processor/mod.rs
src/signer_node/message_processor/process_blockparticipants.rs
src/signer_node/message_processor/process_blocksig.rs
src/signer_node/message_processor/process_blockvss.rs
src/signer_node/message_processor/process_candidateblock.rs
src/signer_node/message_processor/process_completedblock.rs
src/signer_node/mod.rs
src/signer_node/node_parameters.rs
src/signer_node/node_state.rs
src/tests/helper/mod.rs
src/tests/helper/node_parameters_builder.rs
src/tests/helper/node_state_builder.rs
tests/resources/process_blocksig.json

This pull request solves a part of the issue #85.
Use current federation to sign block.
Signers should use proper threshold, public keys, and node_vss which are defined federations-file.
This pull request does not contain the feature that an aggregated public key will be set to block before the federation will change.

Use current federation to sign block

---

snap/snapcraft.yaml

libgmp10 is required run-time.

snap: adjust libraries

---

src/federation.rs
src/signer_node/message_processor/process_blocksig.rs
src/signer_node/message_processor/process_candidateblock.rs
src/signer_node/mod.rs
src/tests/helper/mod.rs
src/tests/helper/node_parameters_builder.rs

This PR fixes two issues.
1. Reported as issue #117. Fixed  in c0979678008490b6ec3c53c74431d2ae24db81d7
2. Panic if the node receives a message when the node is not a member of the current federation. Fixed in b8064c63ac6ea8e62c4b88daa49e8fd1426f5a66

Make tapyrus-signerd possible to start-up if the node is not a member of the current federation.

---

src/signer_node/mod.rs

In testnet, sometimes rounds get time out.

Extend round time limit.

---

doc/configuration.md
src/bin/tapyrus-signerd.rs
src/command_args.rs
src/signer_node/mod.rs
src/signer_node/node_parameters.rs
src/tests/helper/node_parameters_builder.rs
tests/resources/signer_config_sample.toml

This pull request solves https://github.com/chaintope/tapyrus-signer/issues/123
We have two ways to configure the round limit:
- Describe "round-limit" parameter in the signer_config.toml.
- Specify "round-limit" parameter as command line arguments.

Make round limit configurable

---

snap/snapcraft.yaml

as well as chaintope/tapyrus-core#91. Also, make service command line
argument configurable via TAPYRUS_SIGNERD_OPTS environment variable.
Environment variables for tapyrus-signer service is are to be configured
in /etc/environment.

snap: set restart-condition to always

---

doc/configuration.md
src/command_args.rs
tests/resources/signer_config_sample.toml

It was ommited in the documents but exists.

Add a description for `skip-waiting-ibd` option

---

snap/snapcraft.yaml

but set config file path by command line arguments.
Everything should be configured in the config file rather than
overriding by command line arguments. The path of the config file
is the only exception.
----
#132 で `--skip-waiting-ibd` も config ファイルで指定できることがわかったので、必要なオプションはすべて config ファイル内に記述し、サービス起動時コマンドラインオプションからは config ファイルのパスのみを指定することにした。
本来すべての設定はconfigファイルに集約するのが自然で、de6a067903f0bc6b90945d725c98330f082971e5 での対応は `--skip-waiting-ibd` がコマンドラインからしか指定できないと思っていたために入れた間違った対応だった。

snap: quit passing command line arguments via environment variable

---

snap/snapcraft.yaml

Formerly, some build dependencies such as build-essential are not
necessary however it became necessary at some point.
----
以前は build-essential などのビルドに必要なパッケージは明示的に
列挙しなくてもビルド出来ていたが、いつの時点からか明示的に列挙
しないとビルドに失敗するようになった。

snap: declare some build dependencies explicitly in build dependency

---

src/command_args.rs

This pull request improves the codes for parsing command-line arguments(#97)
I told "there are several existing similarities", but I could not find them in the master branch.
Please tell me if you find any problems same as reported in #97.

Simplify parsing command line args

---

snap/snapcraft.yaml

Snap packages for 0.4 tracks should be built from release/v0.4.0 branch.
Specify the target branch explicitly.
Thsi change must not merged into master.

snap: set source-branch to release/v0.4.0

---

src/net.rs
src/signer_node/mod.rs
src/tests/helper/net.rs

This PR solves #59 
Previous implementation is like this:
```rust
main() {
connection_manager.start();
loop {
// handle incoming message.
if connection_error {
panic!()
}
}
}
```
This PR changed to add loop to reconnect.
```rust
main() {
loop {
connection_manager.start();
loop {
// handle incoming message.
if connection_error {
break;
}
}
}
}
```

Reconnect redis

---

.github/workflows/ci.yml
Cargo.lock
Cargo.toml
src/bin/tapyrus-signerd.rs
src/crypto/multi_party_schnorr.rs
src/net.rs
src/rpc.rs
src/signer_node/message_processor/process_candidateblock.rs
src/util.rs

We have received notification from Github about vulnerabilities in dependent libraries and have updated the following libraries to fix the vulnerabilities.
* crossbeam-utils
* lock_api
* hyper
* regex
* miow
* net2
* arc-swap
* smallvec
* thread_local

Apply security patch

---

src/errors.rs
src/federation.rs
src/rpc.rs
src/signer_node/message_processor/mod.rs
src/signer_node/message_processor/process_candidateblock.rs
src/signer_node/mod.rs
src/signer_node/node_parameters.rs
src/signer_node/node_state.rs

As we encode block_height in coinable transaction 'vin[0].prevout.n' block height needs to be u32. Tapyrus-core uses uint32_t.

Change block height from u64 to u32 like tapyrus-core
