src/rpc.rs, src/signer_node.rs
Changed expected return type to `bool` from `unit`.
=> fix: Fix JSON parse error when parse `testproposedblock` response.

.github/workflows/ci.yml, src/bin/node.rs, src/command_args.rs, src/signer_node.rs
=> Make it possible to set coinbase to address as argument.

Cargo.lock, Cargo.toml, src/bin/node.rs, src/util.rs
```
[2019-12-25T08:19:26Z INFO  tapyrus_signer::signer_node] node start. NodeState: Member { block_key: None, shared_block_secrets: {}, block_shared_keys: None, candidate_block: None }, node_index: 2, master_index: 0
[2019-12-25T08:19:26Z TRACE tapyrus_signer::signer_node] No stop signale
[2019-12-25T08:19:26Z TRACE tapyrus_signer::signer_node] No stop signale
[2019-12-25T08:19:27Z TRACE tapyrus_signer::signer_node] No stop signale
[2019-12-25T08:19:27Z TRACE tapyrus_signer::signer_node] No stop signale
[2019-12-25T08:19:27Z TRACE tapyrus_signer::signer_node] No stop signale
[2019-12-25T08:19:28Z TRACE tapyrus_signer::signer_node] No stop signale
[2019-12-25T08:19:28Z TRACE tapyrus_signer::signer_node] No stop signale
^C[2019-12-25T08:19:28Z INFO  tapyrus_signer::signer_node] Signer Node …
```
=> Make the node outputs some logs when the node process stopped by Unix signals

README.md
It was not updated in previous release, so i updated it.
=> Update spec document to current specification

.github/workflows/ci.yml, README.md
=> Use rustc stable version in ci

src/signer_node/mod.rs
Main loop made a lot of logs and it was noisy. So I eliminated such a sort of logs.
=> Eliminate noisy trace log

src/bin/tapyrus-signerd.rs
1. Move into tests module.
2. Make it easy understand with creating a function which returns valid values.
=> Refactoring tapyrus-signerd.rs tests

src/bin/tapyrus-setup.rs, src/blockdata.rs, src/cli/mod.rs, src/cli/setup/create_key.rs, src/cli/setup/mod.rs, src/cli/setup/traits.rs, src/key.rs, src/lib.rs
This pull request implements a command line tool for setting up.
Now `createkey` subcommand is supported.
=> Setup tool(create key)

src/signer_node/message_processor/process_candidateblock.rs, src/signer_node/message_processor/process_completedblock.rs, src/signer_node/mod.rs, src/signer_node/node_parameters.rs, tests/resources/process_blocksig.json
=> Make public key list sort of compressed public key dictionary order.

src/bin/tapyrus-setup.rs, src/cli/setup/create_node_vss.rs, src/cli/setup/mod.rs, src/crypto/vss.rs, src/signer_node/mod.rs, src/signer_node/node_parameters.rs
This pull request adds the feature to create node vss.
Note that the information of vss is not encrypted/decrypted in this version.
I will submit another pull request for it.
=> Support createnodevss subcommand for tapyrus-setup

src/signer_node/mod.rs
This pull request solves a part of the issue #85.
Messages from anyone who is not a member of the federation will ignore.
=> Accept message from federation member only

src/signer_node/message_processor/process_completedblock.rs, src/tests/helper/rpc.rs
=> Make the signerd submits blocks to core when the node receives completedblock message 

src/federation.rs, src/net.rs, src/rpc.rs, src/signer_node/message_processor/process_candidateblock.rs, src/signer_node/message_processor/process_completedblock.rs, src/signer_node/mod.rs, src/signer_node/node_parameters.rs, src/tests/helper/keys.rs, src/tests/helper/mod.rs, src/tests/helper/node_parameters_builder.rs
=> Change the order of TEST_KEYS to dictionary order.

README.md, src/mvs.rs, src/net.rs, src/signer_node/mod.rs, src/tests/helper/mod.rs
This pull request will solve #27
=> Remove Roundfailure message

doc/release-process.md
Signed-off-by: Kohei Taniguchi <kohei@chaintope.com>
=> Update release process

src/net.rs, src/signer_node/message_processor/process_blockparticipants.rs, src/signer_node/message_processor/process_blocksig.rs, src/signer_node/message_processor/process_blockvss.rs, src/signer_node/message_processor/process_candidateblock.rs, src/signer_node/message_processor/process_completedblock.rs
This PR will solve the issue #36 
Add validation to check if the sender of messages receives the message for each message.
=> Ignore received messages sent by own node

snap/snapcraft.yaml
cherry-pick 3 commits from release/v0.4.0 branch.
=> Merge snapcraft changes into master

README.md, src/signer_node/message_processor/process_candidateblock.rs, src/signer_node/mod.rs
Hi, I fixed issue #141 and #113. 
The changes are based on the chage proposal in #141. Check #141 before review, please.
=> Sync node state when candidateblock message received

src/crypto/vss.rs, src/util.rs
This PR replace jacobi function use in vss.rs to one in rust-tapyrus.
This PR is a part of solution for #51
=> Use jacobi function in rust-tapyrus

snap/snapcraft.yaml
Cherry-pick missing part from master.
=> snap: add definition for tapyrus-setup command

snap/snapcraft.yaml
Same as chaintope/tapyrus-core#114.
=> snap: fix architectures specification

src/cli/setup/aggregate.rs
=> Fix output value of aggregate command of tapyrus-setup to compressed public key

doc/setup.md, src/cli/setup/aggregate.rs, src/cli/setup/compute_sig.rs, src/cli/setup/create_block_vss.rs, src/cli/setup/create_node_vss.rs, src/cli/setup/sign.rs
Currently, extended WIF is defined, but what we are using is normal WIF.
=> Fix wif description in setup.md

src/bin/tapyrus-setup.rs, src/command_args.rs
=> Fix cli version option to displays the appropriate version
